force-app/main/default/objects/Mission_Assignment__c/Mission_Assignment__c.object-meta.xml
<CustomObject>
    <label>Mission Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mission Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mission_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;In Progress&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/MissionAssignmentTriggerService.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-15-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public inherited sharing class MissionAssignmentTriggerService {
    
    public static void handleMissionAssignments(){

        Set<Id> missionIds = new Set<Id>();
        Set<Id> missionAssignmentIds = new Set<Id>();
        List<Mission_Assignment__c> misionAssignmentsFailed = new List<Mission_Assignment__c>();

        for(Mission_Assignment__c mAssignment : ((List<Mission_Assignment__c>)Trigger.new)){
            if(Trigger.oldMap.get(mAssignment.Id) != null && 
                ((Mission_Assignment__c)Trigger.oldMap.get(mAssignment.Id)).Status__c != mAssignment.Status__c &&
                mAssignment.Status__c.equalsIgnoreCase('Completed'))
            {
                missionIds.add(mAssignment.Mission__c);
                missionAssignmentIds.add(mAssignment.Id);
            }
        }

        if(!missionIds.isEmpty()){
            for(Mission_Assignment__c mAssignmentItem : [
                SELECT Id, Status__c 
                FROM Mission_Assignment__c 
                WHERE Mission__c IN :missionIds AND Id NOT IN :missionAssignmentIds
            ]){
                mAssignmentItem.Status__c = 'Failed';
                misionAssignmentsFailed.add(mAssignmentItem);
            }
        }

        if(!misionAssignmentsFailed.isEmpty()){
            update misionAssignmentsFailed;
        }
    }

    public static void notifyMissionOwner(){

        List<String> emailsAddresses = new List<String>();
        Set<Id> missionIds = new Set<Id>();

        for(Mission_Assignment__c mAssignment : ((List<Mission_Assignment__c>)Trigger.new)){
            if(Trigger.oldMap.get(mAssignment.Id) != null && 
                ((Mission_Assignment__c)Trigger.oldMap.get(mAssignment.Id)).Status__c != mAssignment.Status__c &&
                mAssignment.Status__c.equalsIgnoreCase('Completed'))
            {
                missionIds.add(mAssignment.Mission__c);
            }
        }

        for(Superhero_Mission__c mission : [SELECT OwnerId, Owner.Email FROM Superhero_Mission__c WHERE Id IN :missionIds]){
            emailsAddresses.add(mission.Owner.Email);
        }

        EmailMessagingService.sendEmails(emailsAddresses, 'Mission Completed', 'COMPLETED');

    }
}