force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/Hero__c.object-meta.xml
<CustomObject>
    <label>Hero</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Heros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Heros</relationshipLabel>
    <relationshipName>Heros</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailMessagingBatch.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-18-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class EmailMessagingBatch implements Database.Batchable<sObject>{
    
    public Set<Id> guildIds;

    public EmailMessagingBatch(Set<Id> guilds){
        guildIds = guilds;
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Contact__c, Contact__r.Email FROM Hero__c WHERE Guild__c IN :guildIds';
        return Database.getQueryLocator(query);
     }
  
     public void execute(Database.BatchableContext BC, List<sObject> scope){
        List<String> emailsAddresses = new List<String>();
        for(Sobject s : scope){
            emailsAddresses.add(((Hero__c)s).Contact__r.Email);
        } 

        if(!emailsAddresses.isEmpty()){
            EmailMessagingService.sendEmails(emailsAddresses, 'Mission Created, please check new advvetures', 'Mission Created');
        }
     }
  
     public void finish(Database.BatchableContext BC){
  
     }

}